apiVersion: v2
name: langfuse
version: 0.2.1-b2c2
description: Open source LLM engineering platform - LLM observability, metrics, evaluations, prompt management.
type: application
keywords:
  - langfuse
  - llm
  - observability
  - prompt management
  - metrics
home: https://langfuse.com/
sources:
  - https://github.com/langfuse/langfuse
  - https://github.com/langfuse/langfuse-k8s
dependencies:
  - name: postgresql
    version: 15.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.deploy
maintainers:
  - name: b2c2
    email: info@b2c2.com
    url: https://b2c2.com/
appVersion: "2"
